# -*- coding: utf-8 -*-
"""final_test1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DkR6-FmR8hJL3czLO1FQnQ7dUC-WaGJX
"""

# Cell 1 – Configuration & Setup
# -------------------------------------------------------------
# Adjust only these – all other cells use these settings dynamically

PRODUCT_CATEGORY = "CLOTHING"   # 🔧 Change to your dataset type
USE_WORDNET_EXPANSION = True    # Expand synonyms for aspects
MAX_SYNONYMS = 3                # Limit per keyword
SAMPLE_MODE = False             # Run small sample for testing
SAMPLE_SIZE = 5000              # Sample size if enabled
SAVE_OUTPUT = True              # Save enriched output CSV
SHOW_PLOTS = True               # Show charts
NEUTRAL_MARGIN = 0.12           # Neutral zone between pos/neg scores

# 🤖 MODEL SELECTION - Choose your sentiment analysis model
# Options: "distilbert", "roberta", "bert", "both"
MODEL_CHOICE = "both"  # ⭐ RECOMMENDED: "both" to compare models

# MODEL DETAILS:
# "distilbert" - Fast, good accuracy (85-90%), simulated neutral
# "roberta"    - Better accuracy (90-94%), native 3-class sentiment, 2x slower
# "bert"       - Best accuracy (92-96%), 5-star rating system, slowest
# "both"       - Run BOTH distilbert and roberta for comparison (RECOMMENDED)

print("✅ Configuration loaded.")
print(f"📊 Model Selection: {MODEL_CHOICE.upper()}")

# Cell 2 – Install & Imports
import subprocess
import sys

# Install packages quietly
packages = ["transformers", "tqdm", "pandas", "matplotlib", "scikit-learn", "nltk", "emoji", "wordfreq", "sentencepiece", "torch"]
for package in packages:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", package])

import os, re, time, json, emoji, torch
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm
from transformers import pipeline
from nltk.corpus import wordnet as wn
import matplotlib.pyplot as plt
from collections import Counter
from sklearn.metrics import classification_report, ConfusionMatrixDisplay
from itertools import chain

import nltk
nltk.download('wordnet', quiet=True)
nltk.download('punkt', quiet=True)

USE_GPU = torch.cuda.is_available()
device = 0 if USE_GPU else -1
print(f"✅ Torch device: {'GPU' if USE_GPU else 'CPU'}")

# Cell 3 – Load Dataset (Local or Colab)
try:
    from google.colab import files
    IN_COLAB = True
except Exception:
    IN_COLAB = False

if IN_COLAB:
    print("📂 Upload your CSV file:")
    uploaded = files.upload()
    import io
    fname = list(uploaded.keys())[0]
    df = pd.read_csv(io.BytesIO(uploaded[fname]))
else:
    fname = "data.csv"
    if os.path.exists(fname):
        df = pd.read_csv(fname)
    else:
        raise FileNotFoundError("No data.csv found in current directory.")

print(f"✅ Loaded dataset → {fname} ({len(df)} rows)")

# Cell 4 – Input Validation & Text Column Detection
import sys

# Ensure DataFrame exists
if 'df' not in globals():
    raise RuntimeError("❌ DataFrame 'df' not found. Please ensure dataset is loaded before validation.")

if len(df) == 0:
    print("❌ ERROR: Dataset is empty. Exiting.")
    sys.exit(1)

# Detect text column - look for common review column names
possible_cols = ["Review", "review", "text", "Text", "comment", "Comment", "feedback", "Feedback", "content", "Content", "reviews"]
text_col = None

for col in possible_cols:
    if col in df.columns:
        text_col = col
        break

if text_col is None:
    # If no match, use the first string column with substantial text
    for col in df.columns:
        if df[col].dtype == 'object':
            avg_length = df[col].astype(str).str.len().mean()
            if avg_length > 20:  # Likely a text column
                text_col = col
                break

if text_col is None:
    raise KeyError(f"❌ Could not find a valid text column. Available columns: {df.columns.tolist()}")
else:
    print(f"✅ Using text column: '{text_col}'")

# Validate and clean
valid_texts = df[text_col].notna() & (df[text_col].astype(str).str.strip() != '')
valid_pct = valid_texts.mean() * 100

if valid_pct < 50:
    print(f"⚠️ WARNING: Only {valid_pct:.1f}% of rows have valid text.")
    print("Continuing anyway; consider reviewing your dataset or adjusting the text column.")

original_len = len(df)
df = df[valid_texts].reset_index(drop=True)
removed = original_len - len(df)

if removed > 0:
    print(f"🧹 Removed {removed} empty/invalid rows ({removed/original_len*100:.1f}%)")

# Handle sample settings
if SAMPLE_MODE and SAMPLE_SIZE is not None and SAMPLE_SIZE < len(df):
    df = df.sample(SAMPLE_SIZE, random_state=42).reset_index(drop=True)
    print(f"📊 Using sample of {len(df)} rows")

print(f"✅ Validation complete. Proceeding with {len(df)} valid rows from column '{text_col}'.")

# Cell 5 – Clean Text
from wordfreq import zipf_frequency

def normalize_text(t):
    t = '' if pd.isna(t) else str(t)
    t = re.sub(r"http\S+|www\.\S+", ' ', t)
    t = re.sub(r"@\w+", ' ', t)
    t = emoji.demojize(t, delimiters=(' ', ' '))
    t = re.sub(r"[^\w\s]", ' ', t)
    t = re.sub(r"\s+", ' ', t).strip()
    return t.lower()

df["clean_text"] = df[text_col].apply(normalize_text)
print("✅ Text cleaning complete.")

# Cell 6 – Sentiment Analysis (Batched inference with confidence)
# MODEL OPTIONS - Choose one:
# 1. DistilBERT (Fast, Good) - DEFAULT
MODEL_NAME = "distilbert-base-uncased-finetuned-sst-2-english"

# 2. RoBERTa (Better accuracy, slower)
# MODEL_NAME = "cardiffnlp/twitter-roberta-base-sentiment-latest"

# 3. BERT (More accurate, slower)
# MODEL_NAME = "nlptown/bert-base-multilingual-uncased-sentiment"

# 4. DistilRoBERTa (Good balance)
# MODEL_NAME = "j-hartmann/emotion-english-distilroberta-base"

print(f"📊 Loading model: {MODEL_NAME}")
sentiment_pipe = pipeline("sentiment-analysis", model=MODEL_NAME, device=device)

def batch_predict_with_confidence(texts, pipe, batch_size=32, neutral_margin=NEUTRAL_MARGIN):
    """Get both labels and confidence in one pass (batched)"""
    labels = []
    confidences = []

    for i in tqdm(range(0, len(texts), batch_size), desc="Analyzing sentiment"):
        batch = texts[i:i+batch_size]
        batch = [str(x) for x in batch]  # ensure all inputs are strings
        batch_results = pipe(batch, truncation=True, max_length=512)

        for result in batch_results:
            score = result.get('score', 0.0)
            label = result.get('label', '').upper()
            confidences.append(score)

            # Normalize label names (different models use different naming)
            if 'POSITIVE' in label or 'POS' in label or label == 'LABEL_2':
                label = 'POSITIVE'
            elif 'NEGATIVE' in label or 'NEG' in label or label == 'LABEL_0':
                label = 'NEGATIVE'
            elif 'NEUTRAL' in label or 'NEU' in label or label == 'LABEL_1':
                label = 'NEUTRAL'

            # For models without native neutral, use threshold
            if label in ['POSITIVE', 'NEGATIVE'] and (0.4 < score < 0.6 or score < neutral_margin):
                labels.append("NEUTRAL")
            else:
                labels.append(label)

    return labels, confidences

# Execute sentiment analysis
df['predicted_label'], df['confidence'] = batch_predict_with_confidence(
    df['clean_text'].tolist(),
    sentiment_pipe
)

print("✅ Sentiment inference complete.")
print(df[['predicted_label', 'confidence']].head())

# Cell 7 – Aspect Extraction + Visualization + Export
CATEGORY_ASPECTS = {
    "ELECTRONICS": ["battery", "camera", "display", "performance", "build quality", "price"],
    "CLOTHING": ["fit", "quality", "style", "comfort", "price"],
    "FOOD": ["taste", "freshness", "quality", "packaging", "price", "delivery"],
    "SKINCARE": ["effectiveness", "texture", "fragrance", "skin reaction", "packaging", "price"],
    "RESTAURANTS": ["food quality", "service", "ambiance", "price", "wait time"],
    "BOOKS": ["plot", "characters", "writing style", "ending", "price"],
    "HOTELS": ["room", "location", "service", "amenities", "price"],
    "APPLIANCES": ["performance", "durability", "noise", "ease of use", "price"],
    "FURNITURE": ["quality", "comfort", "assembly", "design", "price"],
    "TOYS": ["quality", "safety", "entertainment", "educational", "price"],
}

def expand_aspects(aspect_list):
    expanded = set(aspect_list)
    if not USE_WORDNET_EXPANSION:
        return expanded
    for aspect in aspect_list:
        syns = [l.name().replace('_',' ').lower() for s in wn.synsets(aspect) for l in s.lemmas()]
        syns = [s for s in syns if s != aspect][:MAX_SYNONYMS]
        expanded.update(syns)
    return expanded

try:
    base_aspects = CATEGORY_ASPECTS[PRODUCT_CATEGORY.upper()]
except KeyError:
    print(f"⚠️ Unknown category '{PRODUCT_CATEGORY}'. Defaulting to CLOTHING.")
    base_aspects = CATEGORY_ASPECTS["CLOTHING"]

expanded_aspects = expand_aspects(base_aspects)

def extract_aspects(text):
    text = str(text).lower()
    return [a for a in expanded_aspects if re.search(rf"\b{re.escape(a)}\b", text)]

df["aspects"] = df["clean_text"].apply(extract_aspects)
df["aspect_count"] = df["aspects"].apply(len)

# Stats
covered = (df["aspect_count"] > 0).mean() * 100
avg_aspects = df["aspect_count"].mean()
aspect_flat = [a for lst in df["aspects"] for a in lst]
top_aspects = Counter(aspect_flat).most_common(10)

print(f"\n📊 Aspect Summary for {PRODUCT_CATEGORY.title()}")
print(f"• Coverage: {covered:.1f}% reviews with ≥1 aspect")
print(f"• Avg aspects/review: {avg_aspects:.2f}")
print("• Top aspects:", dict(top_aspects))

if SHOW_PLOTS and top_aspects:
    plt.figure(figsize=(8,4))
    plt.bar([a for a, _ in top_aspects], [c for _, c in top_aspects])
    plt.title(f"Top Mentioned Aspects – {PRODUCT_CATEGORY.title()}")
    plt.ylabel("Mentions")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.show()

if "actual_label" in df.columns:
    print("\n🧮 Classification Report:")
    y_true = df["actual_label"]
    y_pred = df["predicted_label"]
    print(classification_report(y_true, y_pred))
    try:
        ConfusionMatrixDisplay.from_predictions(y_true, y_pred)
        plt.show()
    except Exception:
        pass
else:
    print("\n(No actual_label column found – skipping evaluation.)")

if SAVE_OUTPUT:
    out_path = f"sentiment_aspect_output_{PRODUCT_CATEGORY.lower()}.csv"
    df.to_csv(out_path, index=False)
    print(f"💾 Saved enriched dataset → {out_path}")

# Cell 8 – Word Clouds for Sentiment Visualization (OPTIONAL)
try:
    from wordcloud import WordCloud

    def make_wordcloud(subset, label, color):
        if len(subset) == 0:
            return
        text = " ".join(chain.from_iterable(subset["clean_text"].str.split()))
        if not text.strip():
            return
        wc = WordCloud(width=800, height=400, background_color="white", colormap=color).generate(text)
        plt.figure(figsize=(8,4))
        plt.imshow(wc, interpolation="bilinear")
        plt.axis("off")
        plt.title(f"{label} Reviews Word Cloud")
        plt.show()

    if SHOW_PLOTS:
        for sentiment, color in zip(["POSITIVE","NEUTRAL","NEGATIVE"], ["Greens","Blues","Reds"]):
            sub = df[df["predicted_label"] == sentiment]
            if len(sub) > 0:
                make_wordcloud(sub, sentiment, color)
except ImportError:
    print("⚠️ WordCloud not installed. Skipping word clouds. Install with: pip install wordcloud")
except Exception as e:
    print(f"⚠️ Word cloud generation failed: {e}")


print("\n✅ Analysis complete! Check your output file for results.")